//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiscalApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotWords {
            get {
                return ((string)(this["HotWords"]));
            }
            set {
                this["HotWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SempreNoTopo {
            get {
                return ((bool)(this["SempreNoTopo"]));
            }
            set {
                this["SempreNoTopo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1999/XX")]
        public string lastCFOPtyped {
            get {
                return ((string)(this["lastCFOPtyped"]));
            }
            set {
                this["lastCFOPtyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastCodServicotyped {
            get {
                return ((string)(this["lastCodServicotyped"]));
            }
            set {
                this["lastCodServicotyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IA")]
        public string lastCodImpostoIVAtyped {
            get {
                return ((string)(this["lastCodImpostoIVAtyped"]));
            }
            set {
                this["lastCodImpostoIVAtyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string lastRepeatTimesTyped {
            get {
                return ((string)(this["lastRepeatTimesTyped"]));
            }
            set {
                this["lastRepeatTimesTyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal lastQtdePaginasTyped {
            get {
                return ((decimal)(this["lastQtdePaginasTyped"]));
            }
            set {
                this["lastQtdePaginasTyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal lastQtdeItensNFTyped {
            get {
                return ((decimal)(this["lastQtdeItensNFTyped"]));
            }
            set {
                this["lastQtdeItensNFTyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastICMSTyped {
            get {
                return ((string)(this["lastICMSTyped"]));
            }
            set {
                this["lastICMSTyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastIPITyped {
            get {
                return ((string)(this["lastIPITyped"]));
            }
            set {
                this["lastIPITyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal lastCFOPServicoScreenTyped {
            get {
                return ((decimal)(this["lastCFOPServicoScreenTyped"]));
            }
            set {
                this["lastCFOPServicoScreenTyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal lastQtdeRepeatTaxTyped {
            get {
                return ((decimal)(this["lastQtdeRepeatTaxTyped"]));
            }
            set {
                this["lastQtdeRepeatTaxTyped"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\App_Data\\Data" +
            "base.mdf;Integrated Security=True;Connect Timeout=30")]
        public string dbProgram {
            get {
                return ((string)(this["dbProgram"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastCOFINSTyped {
            get {
                return ((string)(this["lastCOFINSTyped"]));
            }
            set {
                this["lastCOFINSTyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastPISTyped {
            get {
                return ((string)(this["lastPISTyped"]));
            }
            set {
                this["lastPISTyped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4500525861")]
        public string NumeroPedido {
            get {
                return ((string)(this["NumeroPedido"]));
            }
            set {
                this["NumeroPedido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01012020")]
        public string DataFatura {
            get {
                return ((string)(this["DataFatura"]));
            }
            set {
                this["DataFatura"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13012020")]
        public string DataLancamento {
            get {
                return ((string)(this["DataLancamento"]));
            }
            set {
                this["DataLancamento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("251479-55")]
        public string NumeroNF {
            get {
                return ((string)(this["NumeroNF"]));
            }
            set {
                this["NumeroNF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2302/AA")]
        public string CFOPTelefonia {
            get {
                return ((string)(this["CFOPTelefonia"]));
            }
            set {
                this["CFOPTelefonia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ValorNFTelefonia {
            get {
                return ((string)(this["ValorNFTelefonia"]));
            }
            set {
                this["ValorNFTelefonia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BaseCalculoTelefonia {
            get {
                return ((string)(this["BaseCalculoTelefonia"]));
            }
            set {
                this["BaseCalculoTelefonia"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\bin\\Debug\\App" +
            "_Data\\Database.mdf;Integrated Security=True;Connect Timeout=30")]
        public string DatabaseConnectionString {
            get {
                return ((string)(this["DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ValorIsentasTelefonia {
            get {
                return ((string)(this["ValorIsentasTelefonia"]));
            }
            set {
                this["ValorIsentasTelefonia"] = value;
            }
        }
    }
}
